import VersoManual
import Cookbook.WorkingWithSyntax.tacticsAsAbbreviationsAndMnemonics
import Cookbook.WorkingWithSyntax.introducingTermsPythonsForComprehensionInLean
import Cookbook.WorkingWithSyntax.introducingCommandsCheckingThatSomethingCanBeProvedByGrind

open Verso.Genre Manual

#doc (Manual) "Working with Syntax" =>
{include 1 Cookbook.WorkingWithSyntax.tacticsAsAbbreviationsAndMnemonics}
{include 1 Cookbook.WorkingWithSyntax.introducingTermsPythonsForComprehensionInLean}
{include 1 Cookbook.WorkingWithSyntax.introducingCommandsCheckingThatSomethingCanBeProvedByGrind}
